### ISSUE TITLE
can't start the bot

### ISSUE THREAD

**Issue by irabro1992** [WeebTime/Video-Encoder-Bot#11]
Hi , i deployed the bot in vps. 
after running the bot , i send /start.
then i got this error. any idea ?
it worked perfectly before.

09-May-22 07:09:24 - pyrogram.dispatcher - ERROR - Invalid parse mode "html"
Traceback (most recent call last):
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/Video-Encoder-Bot/VideoEncoder/plugins/start.py", line 30, in start_message
    await message.reply(text=text, reply_markup=start)
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 959, in reply_text
    return await self._client.send_message(
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/methods/messages/send_message.py", line 122, in send_message
    message, entities = (await utils.parse_text_entities(self, text, parse_mode, entities)).values()
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/utils.py", line 343, in parse_text_entities
    text, entities = (await client.parser.parse(text, parse_mode)).values()
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/parser/parser.py", line 54, in parse
    raise ValueError(f'Invalid parse mode "{mode}"')
ValueError: Invalid parse mode "html"

**Comment by WeebZoneIndia** [comment]
just uninstall pyrogram and install pyrogram==1.4.16
