### ISSUE TITLE
can't set thumbnail

### ISSUE THREAD

**Issue by irabro1992** [WeebTime/Video-Encoder-Bot#12]
when i try to set thumbnail , i got this error message . little help ?

13-May-22 16:17:19 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'file'
Traceback (most recent call last):
  File "/root/Video-Encoder-Bot/venv/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 222, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/Video-Encoder-Bot/VideoEncoder/plugins/thumbnail.py", line 54, in savethumbnail
    mimetype = await get_file_mimetype(tempthumb.name)
  File "/root/Video-Encoder-Bot/VideoEncoder/utils/utils.py", line 55, in get_file_mimetype
    proc = await asyncio.create_subprocess_exec('file', '--brief', '--mime-type', filename, stdout=asyncio.subprocess.PIPE)
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'file'

**Comment by irabro1992** [comment]
still waiting this error to be fixed

**Comment by WeebZoneIndia** [comment]
> still waiting this error to be fixed

Here I'm trying to figure out wtf happened

**Comment by irabro1992** [comment]
> > still waiting this error to be fixed
> 
> Here I'm trying to figure out wtf happened

thread is closed. it means you have already fixed the error ?
i didn't see any update in the script .

**Comment by WeebZoneIndia** [comment]
New update will be added in beta version soon

**Comment by WeebZoneIndia** [comment]
In that thumbnail fix will be included

**Comment by WeebZoneIndia** [comment]
apt-get update && apt-get install -y file
