### ISSUE TITLE
The msg_id is too low, the client time has to be synchronized.

### ISSUE THREAD

**Issue by irabro1992** [WeebTime/Video-Encoder-Bot#28]
its alway working for me. but since tonight , i got this error message,
please check it 

" # bash run.sh
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/Video-Encoder-Bot/VideoEncoder/__main__.py", line 33, in <module>
    app.loop.run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/Video-Encoder-Bot/VideoEncoder/__main__.py", line 28, in main
    await app.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/auth/connect.py", line 47, in connect
    await self.session.start()
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized."

**Comment by irabro1992** [comment]
i upgraded pyrogram version to 2.0.106 and this issue is fixed now.
syncing time is not work with this issue.
